=== blue98060247/XSmlEditor/Assets/Xmls/XSML_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="XMLSchema1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.1"
>
  <xs:element name="Chapter">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Character" type="xs:string" maxOccurs="unbounded"></xs:element>
        <xs:element name="Dialogue" type="xs:string" maxOccurs="unbounded"></xs:element>
        
        <xs:element name="SelectPart" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Options" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name ="OptionCondition" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParamsContent" type="xs:string"></xs:element>
                          <xs:element name="ParamsData" type="xs:int"></xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="OptionString" type="xs:string"></xs:element>
                    <xs:element name="Jump" type="xs:string" minOccurs="0" ></xs:element>
                    <xs:element name="ParamsData" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParamsContent" type="xs:string"></xs:element>
                          <xs:element name="ParamsData" type="xs:int"></xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Dialogue" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                  </xs:sequence>
                </xs:complexType>               
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="chapterID" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== blue98060247/XSmlEditor/Xsml/XMLFile1.xml
<?xml version="1.0" encoding="utf-8" ?>
<Chapter chapterID ="TestChapter"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XSML_Schema.xsd">
  <Character>雷薩</Character>
  <Dialogue>這是測試!</Dialogue>
  <Character>葉希</Character>
  <Dialogue>選擇以下一個選項吧！</Dialogue>
  <SelectPart>
    <Options>
      <OptionString>選項1</OptionString>
      <Dialogue>我選了選項1</Dialogue>
    </Options>
    <Options>
      <OptionString>選項2</OptionString>
      <Dialogue>我選了選項2</Dialogue>
    </Options>
    <Options>
      <OptionString>離開此章節</OptionString>
      <Jump>TestChapterTo</Jump>
      <Dialogue>我選了選項3</Dialogue>
    </Options>
  </SelectPart>
  <Dialogue>測試結束~</Dialogue>
</Chapter>
